server:
  port: 8090


spring:
  data:
    mongodb:
      uri: mongodb+srv://jmtpdev:jmtpdev@testcluster.uosjo.mongodb.net/store_kardex?retryWrites=true&w=majority
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true


springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /api-docs-ui
